# Generated by Django 3.2 on 2021-07-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('steam_id', models.CharField(db_index=True, max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
