# Generated by Django 3.2 on 2021-07-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='isProduction',
            field=models.BooleanField(default=False),
        ),
    ]
