# Generated by Django 3.2 on 2021-07-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_history_isproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='orderID',
            field=models.CharField(default='', max_length=200),
        ),
    ]
